spring.application.name=MARCH

project.name=SB_A5
project.version = 1.0
project.team = A5_BGINNER

project.upcoming[0] = 2.0
project.upcoming[1] = 3.0
project.upcoming[2] = 4.0

project.database[0] = mysql
project.database[1] = oracle
project.database[2] = mssql

project.teams.dev = A5_DEV
project.teams.test = QA
project.teams.usertest = UAT
project.teams.deploy = PROD

spring.profiles.active=prod